name: ArgoCD Create App
description: Template

inputs:
  override_values:
    description: Override values in yaml format
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - name: Commit
      shell: bash
      env:
        OVERRIDE_VALUES: "${{ inputs.override_values }}"
      run: |
        set -xeuo pipefail
        echo "${OVERRIDE_VALUES}"
