
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../../../base/manifests/query-api

namePrefix: test-

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: query-api
      spec:
        template:
          spec:
            containers:
              - name: query-api
                image: image
                env:
                  - name: MILVUS_URL
                    value: "http://10.0.0.94:19530"
                  - name: GOOGLE_PROJECT_ID
                    value: "aqueous-cortex-307813"
  - patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: query-api
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
      spec:
        tls:
          - hosts:
              - "test-query-api.milvus.co-dev-02.heartex.com"
            secretName: "test-query-api.milvus.co-dev-02.heartex.com"

replacements:
  - source:
      kind: Ingress
      name: query-api
      fieldPath: spec.tls.0.hosts.0
    targets:
      - select:
          kind: Ingress
          name: query-api
        fieldPaths:
          - spec.rules.0.host
        options:
          create: true
