name: Build Bundle

on:
  workflow_call:
    inputs:
      sha:
        required: true
        type: string

env:
  # increment it in case if you need to reset cache
  CACHE_NAME_PREFIX: v3
  NODE: '14'

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    # ci can be skipped with `[skip ci]` prefix in message
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: hmarr/debug-action@v2.1.0

      - name: "Checkout codebase"
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.sha }}

      - name: Build distribution package
        run: mkdir build

      # upload this build as artifact to current Action
      - name: Upload bundle
        uses: actions/upload-artifact@v3
        with:
          name: LSF-${{ inputs.sha }}
          path: build/
