name: "Bump Helm Chart Vars"

on:
  workflow_call:
    inputs:
      docker_image_version:
        description: 'Label Studio Enterprise Docker Image version'
        type: string
        required: true
      domain:
        description: 'Domain'
        type: string
        required: true
      namespace:
        description: 'k8s namespace'
        type: string
        required: true
  workflow_dispatch:
    inputs:
      docker_image_version:
        description: 'Label Studio Enterprise Docker Image version'
        type: string
        required: true
      domain:
        description: 'Domain'
        type: string
        required: true
      namespace:
        description: 'k8s namespace'
        type: string
        required: true

env:
  HELM_CHART_VARS_REPO: 'heartexlabs/infra'

jobs:
  bump-helm-chart:
    name: "Bump Helm Chart"
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2.1.0

      - name: Get GitHub user details
        id: get-github-user
        uses: actions/github-script@v6
        env:
          ACTOR_USERNAME: ${{ github.event.sender.login }}
        with:
          github-token: ${{ secrets.GIT_PAT }}
          script: |
            const actor_username = process.env.ACTOR_USERNAME;
            
            let user_name = 'robot-ci-heartex';
            let user_email = 'robot-ci-heartex@users.noreply.github.com';
            
            try {
              const {data: user} = await github.rest.users.getByUsername({
                username: actor_username,
              });
              user_name = user.login;
              user_email = user.email;
            } catch (e) {
              console.log(e)
            }
            
            core.setOutput('user_name', user_name);
            core.setOutput('user_email', user_email);

      - name: Configure git
        shell: bash
        run: |
          set -xeuo pipefail
          git config --global user.name '${{ steps.get-github-user.outputs.user_name }}'
          git config --global user.email '${{ steps.get-github-user.outputs.user_email }}'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ env.HELM_CHART_VARS_REPO }}
          token: ${{ secrets.GIT_PAT }}

      - name: Edit Label Studio Enterprise Helm Chart Vars
        env:
          LSE_CHART_VARS_PATH: "vars/${{ inputs.domain }}/k8s/${{ inputs.namespace }}/values.yaml"
          DOCKER_IMAGE_VERSION: ${{ inputs.docker_image_version }}
        run: |
          yq e --inplace '.global.image.tag |= "${{ inputs.docker_image_version }}"' "${LSE_CHART_VARS_PATH}"          
          cat "${LSE_CHART_VARS_PATH}"

      - name: Commit and Push
        run: |
          git add "${LSE_CHART_VARS_PATH}"
          git commit -m 'Bump LSE ${{ inputs.domain }} in ${{ inputs.namespace }} to ${{ inputs.docker_image_version }}'
          echo git push origin
