name: "Bump Helm Chart Vars"

on:
  workflow_call:
    inputs:
      docker_image_version:
        description: 'Label Studio Enterprise Docker Image version'
        type: string
        required: true
      domain:
        description: 'Domain'
        type: string
        required: true
      namespace:
        description: 'k8s namespace'
        type: string
        required: true
      values_file:
        description: 'k8s yaml file'
        type: string
        required: false
        default: 'values.yaml'
      yaml_key:
        description: 'k8s yaml file key'
        type: string
        required: false
        default: '.global.image.tag'
  workflow_dispatch:
    inputs:
      docker_image_version:
        description: 'Label Studio Enterprise Docker Image version'
        type: string
        required: true
      domain:
        description: 'Domain'
        type: string
        required: true
      namespace:
        description: 'k8s namespace'
        type: string
        required: true
      values_file:
        description: 'k8s yaml file'
        type: string
        required: false
        default: 'values.yaml'
      yaml_key:
        description: 'k8s yaml file key'
        type: string
        required: false
        default: '.global.image.tag'

env:
  HELM_CHART_VARS_REPO_NAME: 'infra'

jobs:
  bump-helm-chart:
    name: "Bump Helm Chart"
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2.1.0

      - name: Get GitHub user details
        id: get-github-user
        uses: actions/github-script@v6
        env:
          ACTOR_USERNAME: ${{ github.event.sender.login }}
        with:
          github-token: ${{ secrets.GIT_PAT }}
          script: |
            const actor_username = process.env.ACTOR_USERNAME;
            
            let user_name = 'robot-ci-heartex';
            let user_email = 'robot-ci-heartex@users.noreply.github.com';
            
            try {
              const {data: user} = await github.rest.users.getByUsername({
                username: actor_username,
              });
              user_name = user.login;
              user_email = user.email;
            } catch (e) {
              console.log(e)
            }
            
            core.setOutput('user_name', user_name);
            core.setOutput('user_email', user_email);

      - name: Configure git
        shell: bash
        run: |
          set -xeuo pipefail
          git config --global user.name '${{ steps.get-github-user.outputs.user_name }}'
          git config --global user.email '${{ steps.get-github-user.outputs.user_email }}'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: "${{ github.repository_owner }}/${{ env.HELM_CHART_VARS_REPO_NAME }}"
          token: ${{ secrets.GIT_PAT }}

      - name: Edit Vector DB values
        env:
          VALUES_FILE_PATH: "vars/${{ inputs.domain }}/k8s/${{ inputs.namespace }}/${{ inputs.values_file }}"
          DOCKER_IMAGE_VERSION: ${{ inputs.docker_image_version }}
        run: |
          yq e --inplace '${{ inputs.yaml_key }} |= "${{ inputs.docker_image_version }}"' "${VALUES_FILE_PATH}"
          cat "${VALUES_FILE_PATH}"

      - name: Commit and Push
        env:
          VALUES_FILE_PATH: "vars/${{ inputs.domain }}/k8s/${{ inputs.namespace }}/${{ inputs.values_file }}"
        run: |
          git add "${VALUES_FILE_PATH}"
          git commit -m 'Bump Vector DB ${{ inputs.domain }} in ${{ inputs.namespace }} to ${{ inputs.docker_image_version }}'  -m 'Workflow run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          git push origin
