name: "CI/CD Pipeline"

on:
  push:
    branches:
      - master
      - 'lse-release/**'
      - 'ls-release/**'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - master
      - 'lse-release/**'
      - 'ls-release/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.pull_request.head.ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build_bundle:
    name: "Build JS Bundle"
    if: github.event_name == 'push' || github.event.pull_request.draft == false
    uses: nikitabelonogov/gh-action-test/.github/workflows/build_bundle.yml@master
    with:
      sha: ${{ github.event.pull_request.head.sha || github.event.after }}
