name: "CI/CD Pipeline"

on:
  push:
    branches:
      - develop
      - 'ls-release/**'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - develop
      - 'ls-release/**'

concurrency:
  group: "CI/CD Pipeline ${{ github.event.pull_request.number || github.event.pull_request.head.ref || github.ref_name }}"
  cancel-in-progress: true

env:
  RELEASE_BRANCH_PREFIX: "ls-release/"

jobs:
  dependabot-auto-merge:
    name: "Changed files"
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    needs:
      - check_gate
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GIT_PAT}}
