name: "CI/CD Pipeline"

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2.1.0

      - name: Commit Release Notes to branch
        id: make-commit
        run: |
          set -euo pipefail
