name: "CI/CD Pipeline"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - develop

concurrency:
  group: "CI/CD Pipeline ${{ github.event.pull_request.number || github.event.pull_request.head.ref || github.ref_name }}"
  cancel-in-progress: true

env:
  RELEASE_BRANCH_PREFIX: "ls-release/"

jobs:
  dependabot-auto-merge:
    name: "Changed files"
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v3.0.0
      - run: echo "${{ github.event.pull_request.head.user.login }}"
      - run: echo "${{ github.head_ref }}"
      - run: echo "${{ startsWith(github.head_ref, 'dependabot/pip/') }}"
