name: "CI/CD Pipeline"

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.pull_request.head.ref || github.ref }}
  cancel-in-progress: true

jobs:
  changed_files:
    name: "Changed files"
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.changes }}
    steps:
      - uses: hmarr/debug-action@v2.1.0

      - name: Checkout
        if: github.event_name == 'push'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            image1:
              - 'image1/**'
            image2:
              - 'image2/**'
            image3:
              - 'image3/**'

  build:
    name: "Build"
    runs-on: ubuntu-latest
    needs:
      - changed_files
    strategy:
      matrix:
        image: ${{ toJSON(needs.changed_files.outputs.changes) }}
    steps:
      - uses: hmarr/debug-action@v2.1.0

      - run: echo ${{ matrix.image }}
