name: "Create ArgoCD Application"

on:
  workflow_call:
    inputs:
      image_version:
        required: true
        type: string
      branch_name:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      image_version:
        description: 'Docker image version'
        required: true
        type: string
      branch_name:
        description: 'Branch name'
        required: true
        type: string

env:
  INFRA_REPO: "nikitabelonogov/gh-action-test"

jobs:

  deploy:
    name: "Environment"
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      deployments: write
    steps:
      - uses: hmarr/debug-action@v2.1.0

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: "HumanSignal/infra"
          token: ${{ secrets.GIT_PAT }}
          depth: 1

      - name: "Validate: base_branch contains a commit"
        shell: bash
        run: |
          set -xeuo pipefail
          git pull
