name: "Deploy env"

on:
  workflow_call:
    inputs:
      image_version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      image_version:
        description: 'Docker image version'
        required: true
        type: string

env:
  HELM_RELEASE_NAMESPACE: milvus
  IMAGE_NAME: "${{ vars.DOCKERHUB_ORG }}/label-studio-query-vectordb"
  GCP_GKE_REGION: "us-east4"
  GCP_GKE_PROJECT: "labelstudio-prod"
  GCP_GKE_CLUSTER_NAME: "dev-lops"

jobs:

  deploy:
    name: "Environment"
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      deployments: write
    steps:
      - uses: hmarr/debug-action@v2.1.0

      - name: Configure gcp credentials
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/902943743985/locations/global/workloadIdentityPools/github-runner/providers/github-runner-provider'
          service_account: 'github-runner@labelstudio-prod.iam.gserviceaccount.com'

      - name: Configure kubeconfig
        shell: bash
        run: |
          gcloud container clusters get-credentials '${{ env.GCP_GKE_CLUSTER_NAME }}' \
            --region '${{ env.GCP_GKE_REGION }}' \
            --project '${{ env.GCP_GKE_PROJECT }}'
          
      - name: Upgrade
        run: kubectl -n '${{ env.HELM_RELEASE_NAMESPACE }}' set image deployment/query-api query-api=${{ env.IMAGE_NAME }}:${{ inputs.image_version }}
