name: "TEST"

on:
  push:

concurrency:
  group: "TEST"
  cancel-in-progress: true


jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v3.0.0

      - name: Merge
        id: merge
        env:
          OUR_FILES: "a b c"
        shell: bash
        run: |
          set -xeuo pipefail
          
          is-ours() {
            local my_variable="$1"
            for e in ${OUR_FILES}; do
              if [[ "${my_variable}" =~ ^"${e}" ]]; then
                  return 0
              fi
            done
            return 1
          }
          
          echo "web/project.json=true" >> $GITHUB_OUTPUT

      - run: echo '${{ steps.merge.outputs.web/project.json }}'
