name: 'Follow Merge: Client Generator'

on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name'
        required: true
        type: string
  # pull_request_target:
  #   types:
  #     - opened
  #     - reopened
  #     - synchronize
  #     - ready_for_review
  #   branches:
  #     - develop
  #     - 'lse-release/**'

concurrency:
  group: ${{ github.workflow }}-${{ inputs.branch_name }}
  cancel-in-progress: true

env:
  POETRY_VERSION: 2.1.4
  DYFF_VERSION: 1.7.0
  CG_PATH: ./label-studio-client-generator
  OPEN_AI_YAML_PATH: fern/openapi/openapi.yaml
  NEW_OPEN_AI_YAML_PATH: openai.new.yaml
  OLD_OPEN_AI_YAML_PATH: openai.old.yaml

jobs:
  spectacular:
    name: Spectacular
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v3.0.0

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: "Humansignal/label-studio-enterprise"
          token: ${{ secrets.GIT_PAT }}
          ref: ${{ inputs.branch_name || github.event.pull_request.head.sha }}
      
      - name: Checkout Actions Hub
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_PAT }}
          repository: HumanSignal/actions-hub
          path: ./.github/actions-hub

      - name: Git Configure
        uses: ./.github/actions-hub/actions/git-configure
        with:
          username: ${{ env.AUTHOR_NAME }}

      - name: "Install poetry"
        run: pipx install "poetry==${{ env.POETRY_VERSION }}"

      - name: "Set up Python"
        id: setup_python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'

      - name: "Install OS dependencies"
        run: |
          sudo apt update
          sudo apt install --no-install-recommends --no-install-suggests -y \
            build-essential python3-dev python3-psutil \
            libffi8 libldap-dev libldap2 libsasl2-dev libssl-dev libgeos-c1v5
  
      - name: Run poetry
        working-directory: ${{ env.LSE_PATH }}
        env:
          POETRY_CACHE_DIR: ~/.cache/pypoetry
        run: poetry install

      - name: Cache dyff binary
        id: cache-dyff
        uses: actions/cache@v4
        with:
          path: ~/.local/bin/dyff
          key: dyff-${{ runner.os }}-${{ env.DYFF_VERSION }}

      - name: Install dyff if not cached
        if: steps.cache-dyff.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.local/bin
          curl -L "https://github.com/homeport/dyff/releases/download/v${DYFF_VERSION}/dyff_${DYFF_VERSION}_linux_amd64.tar.gz" | tar -xz
          mv dyff ~/.local/bin/dyff


      - name: Download Original OpenAI YAML
        id: download-original-openai-yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_PAT }}
          BRANCH_NAME: ${{ inputs.branch_name || github.event.pull_request.head.ref }}
          DEFAULT_BRANCH: master
        run: |
          set -euo pipefail
          # Check if the branch exists in the remote repository 
          if ! git ls-remote --exit-code --heads https://github.com/HumanSignal/label-studio-client-generator.git "${BRANCH_NAME}" > /dev/null; then
            echo "::notice::Branch '${BRANCH_NAME}' does not exist in label-studio-client-generator, using default branch '${DEFAULT_BRANCH}'"
            BRANCH_NAME="${DEFAULT_BRANCH}"
            echo "::set-output name=branch_name::${BRANCH_NAME}"
          fi
          curl -H "Authorization: token ${GITHUB_TOKEN}" -L "https://raw.githubusercontent.com/HumanSignal/label-studio-client-generator/${BRANCH_NAME}/${OPEN_AI_YAML_PATH}" -o "${OLD_OPEN_AI_YAML_PATH}"

      - name: Run Spectacular
        id: spectacular
        shell: bash
        env:
          DJANGO_SETTINGS_MODULE: htx.settings.label_studio
        run: |
          set -euo pipefail

          echo "::group::Run Spectacular"
          poetry run python label_studio_enterprise/manage.py spectacular > "${NEW_OPEN_AI_YAML_PATH}"
          echo "::endgroup::"

          echo "::group::Check if OpenAI YAML is empty"
          if [ -z "$(cat "${NEW_OPEN_AI_YAML_PATH}")" ]; then
            echo "::error::Generated OpenAI YAML is empty"
            exit 1
          fi

          open_ai_dyff=$(dyff between "${OLD_OPEN_AI_YAML_PATH}" "${NEW_OPEN_AI_YAML_PATH}")
          echo "::group::OpenAI Dyff"
          echo "$open_ai_dyff"
          echo "::endgroup::"

          if [ -n "$open_ai_dyff" ]; then
            echo "::error::OpenAI Dyff is not empty"
            echo "::set-output name=changed::true"
          fi

      - name: Checkout client generator
        if: steps.spectacular.outputs.changed == 'true'
        uses: actions/checkout@v4
        with:
          repository: "HumanSignal/label-studio-client-generator"
          path: ${{ env.CG_PATH }}
          token: ${{ secrets.GIT_PAT }}
          ref: ${{ steps.download-original-openai-yaml.outputs.branch_name }}

      - name: Create branch
        if: steps.download-original-openai-yaml.outputs.branch_name == 'master'
        working-directory: ${{ env.CG_PATH }}
        env:
          BRANCH_NAME: "${{ inputs.branch_name || github.event.pull_request.head.ref }}"
        run: git checkout -b "${BRANCH_NAME}"

      - name: Update OpenAI YAML
        if: steps.spectacular.outputs.changed == 'true'
        run: cp "${NEW_OPEN_AI_YAML_PATH}" "${CG_PATH}/${OPEN_AI_YAML_PATH}"

      - name: Commit and push OpenAI YAML
        if: steps.spectacular.outputs.changed == 'true'
        working-directory: ${{ env.CG_PATH }}
        env:
          BRANCH_NAME: "${{ inputs.branch_name || github.event.pull_request.head.ref }}"
        run: |
          git add "${OPEN_AI_YAML_PATH}"
          git commit -m "Update OpenAI YAML"
          git push origin "${BRANCH_NAME}"
