name: "On Premise: Release Pipeline"

on:
  release:
    types:
      - released

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.pull_request.head.ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2.1.0

      - name: test
        run: echo ${{ github.ref_name }}

      - name: test 2
        run: echo ${{ github.event.release.tag_name }}
