name: "PR labeler"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - master
      - 'release/**'

env:
  ACTIONS_STEP_DEBUG: '${{ secrets.ACTIONS_STEP_DEBUG }}'

jobs:
  autolabel:
    name: "PR label validator"
    runs-on: ubuntu-latest
    permissions:
      actions: read|write|none
      checks: read|write|none
      contents: read|write|none
      deployments: read|write|none
      id-token: read|write|none
      issues: read|write|none
      discussions: read|write|none
      packages: read|write|none
      pages: read|write|none
      pull-requests: read|write|none
      repository-projects: read|write|none
      security-events: read|write|none
      statuses: read|write|none
    steps:
      - uses: hmarr/debug-action@v2.1.0
      - uses: thehanimo/pr-title-checker@v1.3.5
        name: "Validate PR's title"
        with:
          GITHUB_TOKEN: ${{ github.token }}
          pass_on_octokit_error: false
          configuration_path: ".github/pr-title-checker-config.json"
      - uses: release-drafter/release-drafter@v5.20.0
        name: "Set PR's label based on title"
        with:
          disable-releaser: true
          config-name: autolabeler.yml
        env:
          GITHUB_TOKEN: ${{ github.token }}
