name: "Selenium"

on:
  schedule:
    - cron: '0 4 * * 1-5'
  workflow_call:
    inputs:
      test_version_ref:
        required: true
        type: string
      test_environment:
        required: true
        type: string
      test_application:
        required: true
        type: string
      url:
        required: true
        type: string
      fflag_env:
        required: true
        type: string
      timeout_minutes:
        required: false
        type: string
        default: "30"
  workflow_dispatch:
    inputs:
      test_version_ref:
        description: 'Ref or SHA'
        required: true
        type: string
        default: 'stable'
      test_environment:
        description: 'Test environment'
        required: true
        type: choice
        default: 'dev'
        options:
          - 'dev'
          - 'qa'
          - 'release'
          - 'prod'
      test_application:
        description: 'Test application'
        required: true
        type: choice
        default: 'enterprise'
        options:
          - 'enterprise'
          - 'open-source-over-saas'
      url:
        description: 'Target url'
        required: true
        type: string
        default: 'https://develop.dev.heartex.com/'
      fflag_env:
        description: 'Fflag env'
        required: true
        type: choice
        default: 'Test'
        options:
          - 'Test'
          - 'OnPremise'
          - 'QA'
          - 'Production'
      timeout_minutes:
        required: false
        type: string
        default: "30"
        description: Configuration for the timeout-minutes parameter of the workflow.

env:
  JDK_VERSION: 17
  JDK_DISTRIBUTION: temurin
  DEFAULT_BRANCH: stable
  DEFAULT_ENV: https://develop.dev.heartex.com/
  TESTS_REPO: heartexlabs/label-studio-test-automation
  SELENIUM_HUB_URL: selenium-grid.dev.heartex.com/wd/hub
  RETRIES: 2
  QA_SLACK_GROUPID: 'S047C5LCF0E'

jobs:

  selenium_tests:
    name: "Selenium"
    timeout-minutes: ${{ inputs.timeout_minutes || 90 }}
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2.1.0
