name: "Test Workflow"

on:
  push:

jobs:
  test:
    name: "test"
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2.1.0

      - name: Check for merge conflict
        id: check-conflict
        shell: bash
        run: |
          set -xeuo pipefail
          if false; then
            echo "merge_conflict=false" >> $GITHUB_OUTPUT
          else
            echo "merge_conflict=true" >> $GITHUB_OUTPUT
          fi

      - name: echo merge conflict
        if: ${{ steps.check-conflict.outputs.merge_conflict }}
        shell: bash
        run: |
          echo '${{ steps.check-conflict.outputs.merge_conflict }}'

      - name: echo merge conflict
        if: ${{ !steps.check-conflict.outputs.merge_conflict }}
        shell: bash
        run: |
          echo '${{ steps.check-conflict.outputs.merge_conflict }}'
