name: "Test"

on:
  workflow_dispatch:
    inputs:
      yes:
        description: 'YES'
        required: true
        default: 'yes'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v3.0.0

      - run: echo ${{ inputs.yes }}

  test2:
    if: inputs.yes == 'yes'
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v3.0.0

      - run: echo ${{ inputs.yes }}
