name: "Test"

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v3.0.0

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - 'scripts/*.py'
