name: "Test"

on:
  push:

jobs:
  test1:
    name: 'test2'
    runs-on: ubuntu-latest
    steps:
      - run: exit 1

  test2:
    name: 'test'
    runs-on: ubuntu-latest
    if: always()
    needs:
      - test1
    steps:
      - name: job.status
        run: echo "${{job.status}}"
      - name: workflow.status
        run: echo "${{workflow.status}}"
