name: "Test"

on:
  workflow_dispatch:
    inputs:
      deploy_to_prod:
        description: 'deploy_to_prod'
        required: true
        default: true
        type: boolean
      sure:
        description: 'sure'
        required: true
        default: 'sure'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v3.0.0

      - run: echo ${{ inputs.deploy_to_prod }} ${{ inputs.sure }}

  test2:
    if: inputs.deploy_to_prod == 'true' && contains(inputs.sure, 'sure')
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v3.0.0

      - run: echo ${{ inputs.deploy_to_prod }} ${{ inputs.sure }}
