name: "Jira: Move issue to QA once pull request is labeled or approved"

on:
  push:

jobs:
  checkout:
    name: 'Checkout w\o sparse'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: "HumanSignal/label-studio"
          ref: "develop"

  checkout-sparse:
    name: 'Checkout w\ sparse'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: "HumanSignal/label-studio"
          ref: "develop"
          sparse-checkout: |
            !label_studio/frontend
            !web/dis
