name: "Move Jira issue to QA once pull request is approved"

on:
  pull_request_review_comment:
    types:
      - created

jobs:
  approved:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2.1.0
