name: "Test"

on:
  push:

jobs:
  test1:
    name: 'test2'
    runs-on: ubuntu-latest
    steps:
      - run: exit 1

  test2:
    name: 'test'
    runs-on: ubuntu-latest
    if: always()
    needs:
      - test1
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: job.status
        run: echo "${{job.status}}"
      - name: github.run_attempt
        env:
          DEBUG: ${{ github.run_attempt > 1 }}
        run: echo "${DEBUG}"
