name: "Test"

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v3.0.0

      - name: Checkout
        uses: actions/checkout@v4

      - name: Create ArgoCD App
        uses: ./.github/actions/test
        with:
          map: |
            FOO=bar
            BAZ=BOO
