name: "test"

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v3.0.0
      - name: "'dependabot[bot]' == 'dependabot[bot]'"
        run: echo "${{ 'dependabot[bot]' == 'dependabot[bot]' }}"
      - run: echo "${{ github.head_ref }}"
      - run: echo "${{ startsWith(github.head_ref, 'dependabot/pip/') }}"
      - run: echo "${{ startsWith(github.head_ref, 'dependabot/npm_and_yarn/') }}"
      - run: echo "${{ ( startsWith(github.head_ref, 'dependabot/npm_and_yarn/') || startsWith(github.head_ref, 'dependabot/pip/') ) }}"
