name: "Jira: Move issue to QA once pull request is labeled"

on:
  label:
    types:
      - created

jobs:
  qa-ready:
    if: github.event.label.name == 'QA'
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2.1.0
