name: "TEST"

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: hmarr/debug-action@v3.0.0

      - name: Checkout Actions Hub
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_PAT }}
          repository: HumanSignal/actions-hub
          path: ./.github/actions-hub

      - name: Generate release changelog
        id: changelog_md
        uses: ./.github/actions-hub/actions/github-generate-changelog
        with:
          release_version: "2.14.1.dev12"
          previous_ref: "tags/2.14.1.dev11"
          current_ref: "52318f488d7d3fc062861efb5ac52e6cbaf5211d"
          github_token: "${{ secrets.GIT_PAT }}"
          jira_server: "https://humansignal.atlassian.net"
          jira_username: "${{ secrets.JIRA_USERNAME }}"
          jira_token: "${{ secrets.JIRA_TOKEN }}"
          jira_release_prefix: "LSE SaaS"
          repository: "HumanSignal/label-studio-enterprise"

      - run: echo "${{ steps.changelog_md.outputs.changelog_msg_b64 }}"
      - run: echo "${{ steps.changelog_md.outputs.changelog_md }}"
      - run: echo "${{ steps.changelog_md.outputs.changelog_json }}"
      - run: echo "${{ env.CHANGELOG_JSON }}"
      - run: echo "${{ env.CHANGELOG_MD }}"
