name: "Test"

on:
  workflow_dispatch:
    inputs:
      client_payload:
        description: "Payload from Zendesk"
        required: true
        type: string

jobs:
  close_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v3.0.0

      - uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GIT_PAT }}
          script: |
            try {
              // Parse the client payload (received from Zendesk)
              const payload = JSON.parse(inputs.client_payload);

              // Log the parsed payload for debugging
              console.log("Parsed payload: ", JSON.stringify(payload, null, 2));
