name: "TEST"

on:
  workflow_dispatch:
  push:

concurrency:
  group: "TEST"
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      matrix: "${{ steps.find-and-close-prs.outputs.matrix }}"
    steps:
      - uses: hmarr/debug-action@v3.0.0

      - name: Find and close Stale PRs
        id: find-and-close-prs
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GIT_PAT }}
          script: |
            const matrix = [1, 2, 4];
            core.setOutput("matrix", matrix);

      - run: echo "${{ steps.find-and-close-prs.outputs.matrix }}"

  test2:
    runs-on: ubuntu-latest
    needs:
      - test
    strategy:
      matrix:
        pr_number: "${{ fromJson(needs.test.outputs.matrix) }}"
    steps:
      - uses: hmarr/debug-action@v3.0.0

      - run: echo "${{ matrix.pr_number }}"
