name: "test"

on:
  push:
    branches:
      - develop

env:
  AUTHOR_NAME: 'robot-ci-heartex'
  OUTFILE: "fern/openapi/openapi.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v3.0.0

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: "HumanSignal/label-studio-client-generator"
          token: ${{ secrets.GIT_PAT }}
          ref: "ci-test"

      - name: Checkout Actions Hub
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_PAT }}
          repository: "HumanSignal/actions-hub"
          path: ./.github/actions-hub

      - name: Git Configure
        uses: ./.github/actions-hub/actions/git-configure
        with:
          username: ${{ env.AUTHOR_NAME }}

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Install swagger2openapi
        run: npm install -g swagger2openapi

      - name: Generate OpenAPI docs
        env:
          CONTAINER_NAME: "lso"
        run: |
          docker run --name "${CONTAINER_NAME}" --rm -p 8080:8080 -d "heartexlabs/label-studio:develop"
          swagger2openapi --yaml --outfile "${{ env.OUTFILE }}" "https://localhost:8080/docs/api?format=openapi"
          docker kill "${CONTAINER_NAME}"

      - name: Commit changes
        env:
          COMMIT_MESSAGE: "Update ${{ env.OUTFILE }}"
          WORKFLOW_LINK: "Workflow run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        run: |
          git add "${{ env.OUTFILE }}"
          git commit -m "${COMMIT_MESSAGE}" -m "${WORKFLOW_LINK}"
          git push
