name: "Jira: Move issue to QA once pull request is labeled or approved"

on:
  push:

jobs:
  qa-ready:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2.1.0
      - run: egrep -q '(-|post)' <<< "1.2.3.post1"
