name: 'Follow Merge: Close Stale PRs'

on:
  workflow_dispatch:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  AUTHOR_NAME: 'robot-ci-heartex'
  AUTHOR_EMAIL: 'robot-ci-heartex@users.noreply.github.com'

jobs:
  findStaleFollowMergePullRequests:
    name: Close Stale PRs
    runs-on: ubuntu-latest
    outputs:
      matrix: "${{ steps.find-stale-fm-prs.outputs.matrix }}"
    steps:
      - uses: hmarr/debug-action@v3.0.0

      - name: Find Stale Follow Merge PRs
        id: find-stale-fm-prs
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GIT_PAT }}
          script: |
            core.startGroup(`Output Matrix`);
            const matrix = {'include': [
              {'pr-number': 1 , 'pr-head-branch': 'foo'},
              {'pr-number': 2 , 'pr-head-branch': 'bar'},
            ]};
            console.log(matrix);
            core.setOutput("matrix", matrix);
            core.endGroup();
            

  updateStaleFollowMergePullRequest:
    runs-on: ubuntu-latest
    if: needs.findStaleFollowMergePullRequests.outputs.martix != '{}'
    needs:
      - findStaleFollowMergePullRequests
    strategy:
      matrix: ${{ fromJson(needs.findStaleFollowMergePullRequests.outputs.matrix) }}
    steps:
      - uses: hmarr/debug-action@v3.0.0
