name: 'Follow Merge: Close Stale PRs'

on:
  workflow_dispatch:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  AUTHOR_NAME: 'robot-ci-heartex'
  AUTHOR_EMAIL: 'robot-ci-heartex@users.noreply.github.com'

jobs:
  findStaleFollowMergePullRequests:
    name: Close Stale PRs
    runs-on: ubuntu-latest
    outputs:
      pr-numbers: "${{ steps.find-stale-fm-prs.outputs.pr-numbers }}"
      pr-head-branches: "${{ steps.find-stale-fm-prs.outputs.pr-head-branches }}"
    steps:
      - uses: hmarr/debug-action@v3.0.0

      - name: Find Stale Follow Merge PRs
        id: find-stale-fm-prs
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GIT_PAT }}
          script: |
            
            core.startGroup(`Output Matrix`);
            const prNumbers = [1, 2];
            const prHeadBranches = ['b1', 'b2'];
            console.log(prNumbers);
            console.log(prHeadBranches);
            core.setOutput("pr-numbers", prNumbers);
            core.setOutput("pr-head-branches", prHeadBranches);
            core.endGroup();
            

  updateStaleFollowMergePullRequest:
    runs-on: ubuntu-latest
    if: needs.findStaleFollowMergePullRequests.outputs.pr-numbers != '[]' || needs.findStaleFollowMergePullRequests.outputs.pr-head-branches != '[]'
    needs:
      - findStaleFollowMergePullRequests
    strategy:
      matrix:
        pr-number: "${{ fromJson(needs.findStaleFollowMergePullRequests.outputs.pr-numbers) }}"
        pr-head-branch: "${{ fromJson(needs.findStaleFollowMergePullRequests.outputs.pr-head-branches) }}"
    steps:
      - uses: hmarr/debug-action@v3.0.0
