name: 'TEST CACHE'

on:
  push:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Docker Buildx
        id: setup-buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Poetry mount
        uses: actions/cache@v4
        with:
          path: /tmp/poetry-cache-alpine
          key: poetry-cache-alpine

      - name: Push Docker image
        uses: docker/build-push-action@v6.18.0
        id: docker_build_and_push
        with:
          context: .
          file: ${{ inputs.docker_file || 'Dockerfile' }}
          push: false
          sbom: true
          provenance: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION_OVERRIDE=${{ steps.version.outputs.image_version }}
            BRANCH_OVERRIDE=${{ inputs.branch_name || github.ref_name }}
            POETRY_VERSION=${{ env.POETRY_VERSION }}
          secrets: |
            "generate_versions_github_token=${{ secrets.GENERATE_VERSIONS_GITHUB_TOKEN }}"
          build-contexts: |
            type=bind,src=/tmp/poetry-cache-alpine,target=/.poetry-cache

      - run: ls -la /tmp/poetry-cache-alpine
