name: "Jira: Move issue to QA once pull request is labeled"

on:
  pull_request_target:
    types:
      - labeled

jobs:
  qa-ready:
#    if: github.event.label.name == 'QA'
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ github.event.label.name }}'
      - uses: hmarr/debug-action@v2.1.0
