name: "Test"

on:
  workflow_dispatch:
    inputs:
      client_payload:
        description: "Payload from Zendesk"
        required: true
        type: string

jobs:
  close_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v3.0.0

      - uses: actions/github-script@v5
        env:
          PAYLOAD: ${{ inputs.client_payload }}
        with:
          github-token: ${{ secrets.GIT_PAT }}
          script: |
            core.startGroup("Parsed payload");
            const payload = JSON.parse(process.env.PAYLOAD);
            core.info(JSON.stringify(payload, null, 2));
            core.endGroup();
