name: "Test"

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'test'
        required: true
        default: 'test'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v3.0.0

      - run: echo ${{ inputs.test }}

  test2:
    if: inputs.test == 'test'
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v3.0.0

      - run: echo ${{ inputs.test }}
