name: "TEST"

on:
  workflow_dispatch:
  push:

concurrency:
  group: "TEST"
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      pr-numbers: "${{ steps.find-and-close-prs.outputs.pr-numbers }}"
      pr-head-branches: "${{ steps.find-and-close-prs.outputs.pr-head-branches }}"
    steps:
      - uses: hmarr/debug-action@v3.0.0

      - name: Find and close Stale PRs
        id: find-and-close-prs
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GIT_PAT }}
          script: |
            const matrix = [1];
            core.setOutput("pr-numbers", [1]);
            core.setOutput("pr-head-branches", ['w']);

      - run: echo "${{ steps.find-and-close-prs.outputs.matrix }}"

  test2:
    runs-on: ubuntu-latest
    needs:
      - test
    strategy:
      matrix:
        pr-number: "${{ fromJson(needs.test.outputs.pr-numbers) }}"
        pr-head-branch: "${{ fromJson(needs.test.outputs.pr-head-branches) }}"
    steps:
      - uses: hmarr/debug-action@v3.0.0

      - run: echo "${{ matrix.pr-number }}"
      - run: echo "${{ matrix.pr-head-branch }}"
