name: "Test"

on:
  push:
    branches:
      - develop
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:

  test:
    if: github.event.pull_request.head.repo.fork != true
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v3.0.0
      - run: echo ${{ github.event.pull_request.head.repo.fork }}
      - run: echo ${{ github.event.pull_request.head.repo.fork == true }}
      - run: echo ${{ github.event.pull_request.head.repo.fork == false }}
