name: "test"

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v3.0.0
      - run: echo "${{ startsWith(github.ref_name, 'deve') && 'OnPremise' || 'Test' }}"
      - run: echo "${{ startsWith(github.ref_name, '1deve') && 'OnPremise' || 'Test' }}"
