name: "TEST"

on:
  workflow_dispatch:
  push:

concurrency:
  group: "TEST"
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      develop-versions: "${{ steps.find-and-close-prs.outputs.develop-versions }}"
    steps:
      - uses: hmarr/debug-action@v3.0.0

      - name: Find and close Stale PRs
        id: find-and-close-prs
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GIT_PAT }}
          script: |
            const developVersions = {
                'label-studio': matchLS.groups.sha,
                'label-studio-evalme': matchEVALME.groups.sha,
                'label-studio-sdk': matchLSSDK.groups.sha,
              };
            core.setOutput("develop-versions", developVersions);

  test2:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: hmarr/debug-action@v3.0.0

      - run: echo "${{ fromJson(needs.test.outputs.develop-versions) }}"
