name: "Test Workflow"

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}

jobs:
  test:
    name: "test"
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2.1.0

      - name: Commit and push
        id: commit_and_push
        continue-on-error: true
        shell: bash
        run: |
          cat << EOF > "/tmp/info_commit_msg"
          multi
          line

          $(date '+%b %d, %Y')
          EOF
          
          {
            echo "commit_msg_file<<EOF"
            cat /tmp/info_commit_msg
            echo "EOF"
          } >> "${GITHUB_OUTPUT}"

          echo "COMMIT_MSG_FILE<<EOF" >> $GITHUB_ENV
          echo "$(cat /tmp/info_commit_msg)" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: GITHUB_OUTPUT
        shell: bash
        run: |
          echo '${{ steps.commit_and_push.outpust.commit_msg_file }}'

      - name: GITHUB_ENV
        shell: bash
        run: |
          echo $COMMIT_MSG_FILE
